### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FluffyDiscord** [tardisx/discord-auto-upload#1]
hey there, it is not working. After settings up I have tried to move some pics to the folder that was being watched but nothing happened

**Comment by tardisx** [comment]
Hi,

What platform are you on?

Can you paste the output you see from the program?

Cheers.

**Comment by FluffyDiscord** [comment]
Thank you for responding.
Here is the screenshot of .bat settings and actual run. It gets stuck there even for hours.
![screenshot_1](https://cloud.githubusercontent.com/assets/10332247/24329666/8219331a-120d-11e7-9127-f5ccf23d5865.jpg)
Using windows 10 64x, with latest discord.

**Comment by tardisx** [comment]
Hi FluffyDiscord. I am so sorry for not getting back to you sooner. I completely missed this message.

I think the problem is that you are dragging existing files into the folder. The software only detects files that have been *created* since the last time it checked. Copying files in windows will preserve the timestamps and thus discord-auto-upload won't "see" them. Definitely, moving them in there will have the same effect (thus, no upload!)

If you want to test, try opening a file with some software, editing it, and doing a "Save As" to the folder - that should work.

Let me know if that doesn't help.
